#!/bin/sh
#
# Copyright (C) 2006 Google. All Rights Reserved.
#
PACKAGE_PATH=$1
INSTALL_PATH=$2
INSTALL_VOLUME=$3
SYSTEM_ROOT=$4

# We originally screwed up the version number in fusefs.fs,
# so until we are > version 1.0, we need to blow this away
# every time :-(
if [ -d $INSTALL_VOLUME/System/Library/Filesystems/fusefs.fs ]
then
  rm -rf $INSTALL_VOLUME/System/Library/Filesystems/fusefs.fs
fi

# We originally installed the kernel extension 
# in /System/Library/Extensions. If it is there before
# this install, then we'll touch just to be sure.
# The actual install process will remove the old extension.
if [ -d $INSTALL_VOLUME/System/Library/Extensions/fusefs.kext ]
then
  touch $INSTALL_VOLUME/System/Library/Extensions
fi

# Signal success
exit 0